apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: gh-ghactions-quay-go-avmaznjp 
  janus-idp.io/tekton: gh-ghactions-quay-go-avmaznjp
  backstage.io/kubernetes-id: gh-ghactions-quay-go-avmaznjp
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: gh-ghactions-quay-go-avmaznjp
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml